# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='task',
            name='pay',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='receiver',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
