# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20181215_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='receiver',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
